version: '2'
services:
    tyk-dashboard:
        image: tykio/tyk-dashboard:latest
        ports:
            - "80:80"   
            - "5000:5000"
        volumes:
            - ./confs/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
        depends_on:
            - tyk-redis
            - tyk-mongo
    tyk-gateway:
        image: tykio/tyk-gateway:latest
        ports:
            - "8181:8181"
        volumes:
            - ./confs/tyk.conf:/opt/tyk-gateway/tyk.conf
        depends_on:
            - tyk-redis
    tyk-pump:
        image: tykio/tyk-pump-docker-pub:latest
        volumes:
            - ./confs/pump.conf:/opt/tyk-pump/pump.conf
        depends_on:
            - tyk-redis
            - tyk-mongo
            - tyk-gateway
    tyk-redis:
        image: redis
        ports:
            - "6379:6379"
    tyk-mongo:
        image: mongo
        ports:
            - "27017:27017"
